### ISSUE TITLE
抗重放

### ISSUE THREAD

**Issue by weizhen199** [cop-cos/COP#1]
https保证抗重放的
https://security.stackexchange.com/questions/20105/are-ssl-encrypted-requests-vulnerable-to-replay-attacks

http下抗重放，我没看过服务端的实现代码，从请求这边来看，时间的header有做digest吗，貌似能伪造

**Comment by louchsh** [comment]
X-Coscon-Hmac的摘要里面包含了时间信息，无法伪造的。

**Comment by weizhen199** [comment]
看到了，在X-Coscon-Authorization里
